"""Удалил ненужную таблицу followers

Revision ID: 99a5e3cad12a
Revises: 12470b4110db
Create Date: 2024-07-25 16:31:13.218595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99a5e3cad12a'
down_revision = '12470b4110db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followed_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], name='followers_followed_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], name='followers_follower_id_fkey'),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id', name='followers_pkey')
    )
    # ### end Alembic commands ###
